# Generated by Django 4.2.27 on 2025-12-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borroweruser",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="borroweruser",
            name="borrower",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_user",
                to="management.borrower",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name="borroweruser",
            name="permission",
        ),
    ]
