# Generated by Django 4.2.27 on 2025-12-13 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "management",
            "0002_alter_borroweruser_unique_together_remove_user_role_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashforecastrow",
            name="report",
        ),
        migrations.DeleteModel(
            name="CashFlowForecastRow",
        ),
        migrations.DeleteModel(
            name="CashForecastRow",
        ),
    ]
