# Generated by Django 4.2.27 on 2025-12-13 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_remove_cashforecastrow_report_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
