# Generated by Django 4.2.27 on 2025-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
