# Generated by Django 5.0.14 on 2026-01-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_bbc_availability'),
        ('management', '0004_value_trend'),
    ]

    operations = [
    ]
