# Generated by Django 5.0.14 on 2026-01-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_merge_0004_bbc_availability_0004_value_trend'),
        ('management', '0005_net_recovery_trend'),
    ]

    operations = [
    ]
