# Generated by Django 4.2.27 on 2025-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_borrower_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="collateraloverviewrow",
            name="snapshot_summary",
            field=models.TextField(blank=True, null=True, verbose_name="Snapshot Summary"),
        ),
    ]
