# Generated by Django 4.2.27 on 2025-12-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_collateral_overview_snapshot_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                db_column="company_email",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="password",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                db_column="company_password",
            ),
        ),
    ]
