# Generated by Django 5.0.14 on 2026-01-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_borrower_unique_company_contact'),
        ('management', '0006_merge_20260103_0249'),
    ]

    operations = [
    ]
