# Generated by Django 4.2.27 on 2025-12-23 00:20

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations


def add_missing_borrower_columns(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    for model in apps.get_models():
        if model._meta.app_label != "management":
            continue
        if not model._meta.managed:
            continue
        try:
            field = model._meta.get_field("borrower")
        except FieldDoesNotExist:
            continue

        table = model._meta.db_table
        if table not in existing_tables:
            continue

        with connection.cursor() as cursor:
            columns = {
                col.name
                for col in connection.introspection.get_table_description(cursor, table)
            }
        if field.column in columns:
            continue

        schema_editor.add_field(model, field)


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0007_company_email_password"),
    ]

    operations = [
        migrations.RunPython(add_missing_borrower_columns, migrations.RunPython.noop),
    ]
