# Generated by Django 4.2.27 on 2025-12-23 01:00

from django.db import migrations


def ensure_top20_tables(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    for model_name in ("Top20ByTotalARRow", "Top20ByPastDueRow"):
        model = apps.get_model("management", model_name)
        table = model._meta.db_table

        if table not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(table)
            continue

        field = model._meta.get_field("report")
        with connection.cursor() as cursor:
            columns = {
                col.name
                for col in connection.introspection.get_table_description(
                    cursor, table
                )
            }
        if field.column in columns:
            continue

        schema_editor.add_field(model, field)


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0009_reintroduce_cash_forecasts"),
        ("management", "0009_remove_borrowerreport_borrower_and_more"),
    ]

    operations = [
        migrations.RunPython(ensure_top20_tables, migrations.RunPython.noop),
    ]
