# Generated by Django 5.2.9 on 2025-12-23 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0010_merge_0009_reintroduce_cash_forecasts_borrowerreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="top20bypastduerow",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_rows",
                to="management.borrowerreport",
            ),
        ),
        migrations.AlterField(
            model_name="top20bytotalarrow",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_rows",
                to="management.borrowerreport",
            ),
        ),
    ]
