# Generated by Codex on 2025-02-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_alter_top20bypastduerow_report_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotSummaryRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("accounts_receivable", "Accounts Receivable"),
                            ("inventory_summary", "Inventory Summary"),
                            ("risk", "Risk"),
                            ("forecast_liquidity", "Forecast - Liquidity"),
                            ("forecast_sales_gm", "Forecast - Sales & Gross Margin"),
                            ("forecast_ar", "Forecast - Accounts Receivable"),
                            ("forecast_inventory", "Forecast - Inventory"),
                            ("week_summary", "Weekly Summary"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(blank=True, null=True, verbose_name="Snapshot Summary"),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_summaries",
                        to="management.borrower",
                    ),
                ),
            ],
            options={
                "db_table": "snapshot_summaries",
                "unique_together": {("borrower", "section")},
            },
        ),
    ]
