# Generated by Django 5.2.9 on 2025-12-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0012_snapshot_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="borrower",
            name="primary_naics",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="borrower",
            name="primary_specific_individual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_borrowers",
                to="management.specificindividual",
            ),
        ),
        migrations.AddField(
            model_name="borrower",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="lender_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="lender_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="specific_individual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="specific_individual_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="lender_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="update_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Annual", "Annual"),
                    ("Semi-Annual", "Semi-Annual"),
                    ("Quarterly", "Quarterly"),
                    ("Monthly", "Monthly"),
                    ("Weekly", "Weekly"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="primary_naics",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="snapshotsummaryrow",
            name="section",
            field=models.CharField(
                choices=[
                    ("accounts_receivable", "Accounts Receivable"),
                    ("inventory_summary", "Inventory Summary"),
                    ("other_collateral", "Other Collateral"),
                    ("risk", "Risk"),
                    ("forecast_liquidity", "Forecast - Liquidity"),
                    ("forecast_sales_gm", "Forecast - Sales & Gross Margin"),
                    ("forecast_ar", "Forecast - Accounts Receivable"),
                    ("forecast_inventory", "Forecast - Inventory"),
                    ("week_summary", "Weekly Summary"),
                ],
                max_length=64,
            ),
        ),
    ]
