# Generated by Codex on 2025-02-14

import django.db.models.deletion
from django.db import migrations, models


def backfill_cash_forecast_borrowers(apps, schema_editor):
    CashForecastRow = apps.get_model("management", "CashForecastRow")
    CashFlowForecastRow = apps.get_model("management", "CashFlowForecastRow")

    def populate(model_cls):
        batch = []
        qs = model_cls.objects.filter(borrower__isnull=True, report__isnull=False).select_related(
            "report__borrower"
        )
        for row in qs.iterator():
            report = row.report
            if report and report.borrower_id:
                row.borrower_id = report.borrower_id
                batch.append(row)
            if len(batch) >= 500:
                model_cls.objects.bulk_update(batch, ["borrower"])
                batch = []
        if batch:
            model_cls.objects.bulk_update(batch, ["borrower"])

    populate(CashForecastRow)
    populate(CashFlowForecastRow)


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0013_borrower_industry_borrower_primary_naics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashforecastrow",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_forecast",
                to="management.borrower",
            ),
        ),
        migrations.AddField(
            model_name="cashflowforecastrow",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_flow_forecast",
                to="management.borrower",
            ),
        ),
        migrations.RunPython(backfill_cash_forecast_borrowers, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="cashforecastrow",
            index=models.Index(fields=["borrower", "report"], name="cash_foreca_borrower_report_idx"),
        ),
        migrations.AddIndex(
            model_name="cashflowforecastrow",
            index=models.Index(fields=["borrower", "report"], name="cash_flow_fore_borrower_report_idx"),
        ),
    ]
