# Generated by Django 5.2.7 on 2025-12-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(max_length=255)),
                ('primary_contact_name', models.CharField(max_length=255)),
                ('primary_contact_phone', models.CharField(max_length=20)),
                ('primary_contact_email', models.EmailField(max_length=255)),
                ('update_interval', models.CharField(max_length=50)),
                ('current_update', models.DateField()),
                ('previous_update', models.DateField()),
                ('next_update', models.DateField()),
                ('lender_name', models.CharField(max_length=255)),
                ('lender_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_id', models.BigIntegerField(unique=True)),
                ('industry', models.CharField(max_length=255)),
                ('primary_naics', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(max_length=255)),
                ('sub_type', models.CharField(max_length=255)),
                ('beginning_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ineligibles_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('eligible_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nolv_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dilution_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('advanced_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utilized_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pre_reserve_collateral', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collateral_reserves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_collateral', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='core.borrower')),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='core.company'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=255)),
                ('as_of_date', models.DateField()),
                ('bucket', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_of_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='core.division')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=50)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='core.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('fair_market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('orderly_liquidation_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_values', to='core.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orderly_liquidation_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_asset_count', models.IntegerField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation_values', to='core.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('individual_id', models.CharField(max_length=50)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_individuals', to='core.borrower')),
            ],
        ),
    ]
